# Generated by Django 5.0.6 on 2024-06-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Машина')),
                ('number_car', models.CharField(max_length=30, verbose_name='Номер машины')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
                ('mileage_before_maintenance', models.FloatField(blank=True, null=True, verbose_name='Пробега для ТО')),
                ('mileage', models.FloatField(blank=True, null=True, verbose_name='Пробег')),
                ('maintenance_info', models.TextField(blank=True, null=True, verbose_name='Что нужно для ТО')),
                ('photo', models.ImageField(default='cars/1.png', upload_to='cars', verbose_name='Фото')),
                ('extension_number', models.IntegerField(default=0, verbose_name='Внутренний номер')),
                ('work_area', models.CharField(default=' ', max_length=100, verbose_name='Зона работы')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='FirmCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фирма')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
                ('telegram_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграм ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.car', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='firm_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.firmcar', verbose_name='Фирма машины'),
        ),
        migrations.CreateModel(
            name='FuelBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30, verbose_name='Цена')),
                ('volume', models.CharField(max_length=30, verbose_name='Объём')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Фактура за бензин',
                'verbose_name_plural': 'Фактуры за бензин',
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('mileage_car_start', models.FloatField(blank=True, null=True, verbose_name='Начальный пробег')),
                ('mileage_car_end', models.FloatField(blank=True, null=True, verbose_name='Конечный пробег')),
                ('mileage_car_difference', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Пробег за смену')),
                ('start_trip', models.DateTimeField(blank=True, null=True, verbose_name='Начало смены')),
                ('end_trip', models.DateTimeField(blank=True, null=True, verbose_name='Конец смены')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность смены')),
                ('chat_id', models.CharField(blank=True, max_length=20, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.car', verbose_name='Машина')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
    ]
